//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KisiselVeriler.DAL.KisiselVerilerDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AileBilgileri
    {
        public int AileBilgileriID { get; set; }
        public int KisiID { get; set; }
        public string AnneAdi { get; set; }
        public string BabaAdi { get; set; }
        public Nullable<byte> KardesSayisi { get; set; }
    
        public virtual KisiselBilgiler KisiselBilgiler { get; set; }
    }
}
