//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KisiselVeriler.DAL.KisiselVerilerDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EgitimBilgileri
    {
        public int KisiID { get; set; }
        public string Ilkokul { get; set; }
        public string Ortaokul { get; set; }
        public string Lise { get; set; }
        public string Universite { get; set; }
    
        public virtual KisiselBilgiler KisiselBilgiler { get; set; }
    }
}
