//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KisiselVeriler.DAL.KisiselVerilerDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hobiler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hobiler()
        {
            this.KisiHobileri = new HashSet<KisiHobileri>();
        }
    
        public int HobiID { get; set; }
        public string HobiAdi { get; set; }
        public Nullable<int> HobiUstKategoriID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KisiHobileri> KisiHobileri { get; set; }
    }
}
