//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KisiselVeriler.DAL.KisiselVerilerDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class KisiselBilgiler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KisiselBilgiler()
        {
            this.AileBilgileri = new HashSet<AileBilgileri>();
            this.IletisimBilgileri = new HashSet<IletisimBilgileri>();
            this.KisiHobileri = new HashSet<KisiHobileri>();
        }
    
        public int KisiID { get; set; }
        public string KisiAdi { get; set; }
        public string KisiSoyadi { get; set; }
        public string KisiTCNo { get; set; }
        public System.DateTime KisiDogumTarihi { get; set; }
        public string KisiDogumYeri { get; set; }
        public string KisiUyruk { get; set; }
        public Nullable<decimal> KisiAylikGelir { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AileBilgileri> AileBilgileri { get; set; }
        public virtual EgitimBilgileri EgitimBilgileri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IletisimBilgileri> IletisimBilgileri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KisiHobileri> KisiHobileri { get; set; }
    }
}
