//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KisiselVeriler.DAL.KisiselVerilerDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KisiselVerilerDBContext : DbContext
    {
        public KisiselVerilerDBContext()
            : base("name=KisiselVerilerDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AileBilgileri> AileBilgileri { get; set; }
        public virtual DbSet<EgitimBilgileri> EgitimBilgileri { get; set; }
        public virtual DbSet<Hobiler> Hobiler { get; set; }
        public virtual DbSet<IletisimBilgileri> IletisimBilgileri { get; set; }
        public virtual DbSet<KisiHobileri> KisiHobileri { get; set; }
        public virtual DbSet<KisiselBilgiler> KisiselBilgiler { get; set; }
    }
}
